name: Artifact

on:
  push:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Create report file
        run: |
          echo "log file in workflow" > report.txt
          echo "Run ID: ${{ github.run_id }}" >> report.txt
          echo "Current date and time: $(date)" >> report.txt
          echo "Commit: ${{ github.sha }}" >> report.txt
          echo "Repository: $GITHUB_REPOSITORY" >> report.txt
          echo "Actor: $GITHUB_ACTOR" >> report.txt

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.txt
          path: report.txt
          if-no-files-found: error
