name: deploy after test

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: verify
       run: |
         if ${{ github.event.workflow_run.conclusion == 'success' }}
           echo "workflow run successful"
         else
           echo "Tests did not succeed."
           echo "Skipping to deploy."
           exit 1
         fi 
