name: manual Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: the env where this will run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - main
          
jobs:
 manual-job:
   runs-on: ubuntu-latest
   steps:
     - name: print the env
       run: |
        echo "The environment: ${{ inputs.environment }}"
