name: multi-job

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print output
        run: echo "Building the app"
  Test:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: print output
        run: echo "Runnning Tests"
  deploy:
    runs-on: ubuntu-latest
   ## needs: Test
    steps:
      - name: print output
        run: echo "Deploying"
