name: PR Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: |
          echo "PRs check running for branch: ${{ github.head_ref }}"


