name: Reusable Build

on:
  workflow_call:
    inputs:
      app_name:
        description: "Name of the application"
        type: string
        required: true
      environment: 
        description: "Env for deployment"
        required: true
        type: string
        default: "staging"

    secrets:
      docker_token:
        required: true

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether docker token exists
        run: |
          if [ -n "${{ secrets.DOCKER_TOKEN}}" ]; then
            echo "The docker token is set: true"
          else
            echo "The docker token is set: false"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        run: |
          echo "Building ${ { inputs.app_name } } for ${ { inputs.environment } }"
          
