name: Daily Schedule

on: 
  schedule:
    - cron: '0 0 * * *'
jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - print: schedule message
        run: echo "workflow run everyday at mid night"
