name: Secrets as Env

on:
  workflow_dispatch:
  push:

jobs:
  secret-env:
    runs-on: ubuntu-latest

    steps:

      - name: Check Docker secrets are available
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_TOKEN" ]; then
            echo "Docker credentials are configured."
          else
            echo "Docker credentials are missing."
            exit 1
          fi
