name: Self-Hosted Runner Test

on: [push]

jobs:
  self-hosted:
    runs-on: self-hosted
    steps: 
      - name: task 
        run: |
          hostname  
          pwd
          echo -e '#!/bin/bash\necho "Hello from runner!"' > /actions-runner/_work/github-actions-practice/github-actions-practice/hello.sh
          sudo chmod +x hello.sh
          sudo ./hello.sh
