name: Self-Hosted Runner Test

on: [push]

jobs:
  self-hosted:
    runs-on: self-hosted
    steps: 
      - name: task 
        run: |
          hostname  
          pwd
          echo "Hello from my runner!" > /tmp/runner-test.txt
          ls -la /tmp/runner-test.txt
