name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
      - uses: actions/checkout@v4

      - name: test run output
        run: |
          echo "Running tests..."
          echo "All tests passed."
